CREATE DATABASE SENSELESS CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE SENSELESS;

CREATE TABLE IF NOT EXISTS game_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    story_key VARCHAR(50) NOT NULL,
    story_text TEXT NOT NULL,
    next_choices TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    found_at VARCHAR(50) NOT NULL,
    found_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);